function params = preprocAppendModel_GetMetaParams(argNum)
% Usage: params = preprocAppendModel_GetMetaParams(argNum)
% 
% Return preset parameters for preprocAppendModel, i.e. model query
% parameters for models to append. NOTE THAT THIS WORKS SUBSTANTIALLY
% DIFFERENTLY FROM OTHER PREPROC<X>_GETMETAPARAMS FUNCTIONS, in that it
% explicitly relies on the use of a database.
% 
% Different "argNum"s will specify the StimClass of the stimulus for the
% model, as well as the preprocessing sequence, but NOT the experiment name
% / session / training vs validation status; the function
% preprocAppendModel relies on a PreprocessedStimulus input (rather than a
% raw numerical matrix) to fill in those parameters. 
% 
% ML 2013.05

params.class = 'preprocAppendModel';
switch argNum
    case 1
        % RMS contrast, no TF channels
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'RGB';
        params.ppSeqToAdd = {'preprocColorSpace',1,...
                        'preprocRMS',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    case 2
        % RMS contrast, w/ TF channels
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'RGB';
        params.ppSeqToAdd = {'preprocColorSpace',1,...
                        'preprocRMS',1,...
                        'preprocTF',6,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    %%% --- Object Normals -> aborted exploration in favor of silhouettes --- %%%
    case 3
        % No-orientation contour contrast, w/ TF channels
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'ObNormals';
        params.ppSeqToAdd = {'preprocNormalGradient',1,...
                        'preprocWavelets_grid',10,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    
    case 4
        % No-orientation contour contrast, w/ TF channels
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'ObNormals';
        params.ppSeqToAdd = {'preprocNormalGradient',1,...
                        'preprocWavelets_grid',9,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    %%% --- Silhouettes. Add all flavors --- %%%
    case 5
        % (sm model, mod 1) +ori +pyr +tf
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Zmask';
        params.ppSeqToAdd = {'preprocGradient',1,...
                        'preprocWavelets_grid',1,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};

    case 6
        % (lg model, mod 2) +ori +pyr +tf
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Zmask';
        params.ppSeqToAdd = {'preprocGradient',1,...
                        'preprocWavelets_grid',2,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    case 7
        % (sm model, mod 1) +ori -pyr +tf
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Zmask';
        params.ppSeqToAdd = {'preprocGradient',1,...
                        'preprocWavelets_grid',3,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};

    case 8
        % (lg model, mod 1) +ori -pyr +tf
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Zmask';
        params.ppSeqToAdd = {'preprocGradient',1,...
                        'preprocWavelets_grid',4,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    case 9
        % (sm model, mod 1) -ori +pyr +tf
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Zmask';
        params.ppSeqToAdd = {'preprocGradient',1,...
                        'preprocWavelets_grid',9,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    case 10
        % (lg model, mod 2) -ori +pyr +tf
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Zmask';
        params.ppSeqToAdd = {'preprocGradient',1,...
                        'preprocWavelets_grid',10,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    case 11
        % smaller, w/ orientation, pyramid, no TF
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Zmask';
        params.ppSeqToAdd = {'preprocGradient',1,...
                        'preprocWavelets_grid',5,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    case 12
        % larger, w/ orientation, pyramid, no TF
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Zmask';
        params.ppSeqToAdd = {'preprocGradient',1,...
                        'preprocWavelets_grid',6,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    case 13
        % smaller, + ori, - pyr, - TF
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Zmask';
        params.ppSeqToAdd = {'preprocGradient',1,...
                        'preprocWavelets_grid',7,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};

    case 14
        % larger, + ori, - pyr, - TF
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Zmask';
        params.ppSeqToAdd = {'preprocGradient',1,...
                        'preprocWavelets_grid',8,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    case 15
        % larger, -or -pyr -TF
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Zmask';
        params.ppSeqToAdd = {'preprocGradient',1,...
                        'preprocWavelets_grid',22,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};

                    %%%%
    case 21
        % smaller, w/ orientation, pyramid, no TF
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Normals';
        params.ppSeqToAdd = {'preprocNormalGradient',1,...
                        'preprocWavelets_grid',5,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    case 22
        % larger, w/ orientation, pyramid, no TF
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Normals';
        params.ppSeqToAdd = {'preprocNormalGradient',1,...
                        'preprocWavelets_grid',6,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    case 23
        % smaller, + ori, - pyr, - TF
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Normals';
        params.ppSeqToAdd = {'preprocNormalGradient',1,...
                        'preprocWavelets_grid',7,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};

    case 24
        % larger, + ori, - pyr, - TF
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Normals';
        params.ppSeqToAdd = {'preprocNormalGradient',1,...
                        'preprocWavelets_grid',8,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    case 25
        % larger, -or -pyr -TF
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Normals';
        params.ppSeqToAdd = {'preprocNormalGradient',1,...
                        'preprocWavelets_grid',22,...
                        'preprocNonLinearOut',1,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    case 26
        % WordNet 1.1
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'WordNetLabels_1.1';
        params.ppSeqToAdd = {'preprocDownsample',1};
    case 27
        % Scene Depth/Normals, w/ no TF processing
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'MultiComponent';
        params.ppSeqToAdd = {'preprocSceneDepthNormals',7,...
                        'preprocDownsample',1,...
                        'preprocNormalize',1};
    case 28
        % 39 Background categories from BVP ses 1
        params.LeftRight = 'Right';
        params.stimToAdd.StimClass = 'Backgrounds';
        params.ppSeqToAdd = {'preprocDownsample',1};
end